#!/bin/bash
#
# btrfs-snapshot - tool for creating btrfs snapshots
#

declare -r filename=${0##*/} version=%VERSION%

_f_functions=functions
_d_configs=btrfs-snapshot

_optconfig= _optdest= _optsubvol=
_optnkeep=0 _optwritable=0

usage() {
    cat <<EOF
btrfs-snapshot $version
usage: $filename [options]

  Options:
   -c, --config <config>            Use specified config file in /etc/btrfs-snapshot
   -C, --allconfigs                 Process all config files in /etc/btrfs-snapshot (default: yes)
   -d, --dest <dir>                 Destination for snapshot
   -h, --help                       Display this message and exit
   -n, --nkeep <number>             Limit number of snapshots to keep (default: no)
   -V, --version                    Display version information and exit
   -s, --subvol <path>              Path to subvolume
   -w, --writable                   Create a writable snapshot (default: no)

EOF
}

version() {
    cat <<EOF
btrfs-snapshot $version
EOF
}

check_config() {
    local -i _code=0
    if [[ $ ]]; then
        [[ $subvol ]] || {
            echo "$filename: requires option '-s'"
            _code=1
        }
        [[ $dest ]] || {
            echo "$filename: requires option '-d'"
            _code=1
        }
    else
        [[ $subvol ]] || {
            echo "$filename: requires variable 'subvol'"
            _code=1
        }
        [[ $dest ]] || {
            echo "$filename: requires variable 'dest'"
            _code=1
        }
    fi
    [[ $_code == 0 ]] || exit $_code
}

check_dest() {
    mkdir -p "$dest"
    snapshot=$dest/$(date -I)
    [[ ! -d $snapshot ]] || {
        echo "$filename: snapshot in \`$dest' already exists"
        return 1
    }
}

create() {
    if [[ $writable == true ]]; then
        btrfs subvolume snapshot "$subvol" "$snapshot"
    else
        btrfs subvolume snapshot -r "$subvol" "$snapshot"
    fi
}

delete() {
    local _ndel=$(( $(ls "$dest" | wc -l) - nkeep ))
    (( _ndel <= 0 )) || {
        local _snapshot=()
        mapfile -t _snapshot < <(ls -d "$dest"/* | head -n $_ndel)
        btrfs subvolume delete "${_snapshot[@]}"
    }
}

main() {
    check_config
    check_dest || return
    create || return
    if [[ $nkeep ]]; then
        delete
    else
        return 0
    fi
}

. "$_f_parseopts"

trap 'exit 130' INT
trap 'exit 143' TERM

_opt_short='c:Cd:hn:Vs:w'
_opt_long=('config:' 'allconfigs' 'dest:' 'help'
          'nkeep:' 'version' 'subvol:' 'writable')

parseopts "$_opt_short" "${_opt_long[@]}" -- "$@" || exit 1
set -- "${OPTRET[@]}"
unset _opt_short _opt_long OPTRET

while :; do
    case $1 in
        -c|--config)
            shift
            _d_config=$1
            _optconfig=+=("$1")
            ;;
        -C|--allconfigs)
            _optconfig=("$_d_configs"/*.conf)
            [[ -e ${_optpreset[0]} ]] || die "No config files found in $_d_presets"
            ;;
        -d|--dest)
            shift
            _optdest=$1
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        -n|--nkeep)
            shift
            declare -i _optnkeep=$1
            ;;
        -V|--version)
            version
            exit 0
            ;;
        -s|--subvol)
            shift
            _optsubvol=$1
            ;;
        -w|--writable)
            _optwritable=1
            ;;
        --)
            shift
            break 2
            ;;
    esac
    shift
done

if [[ $confdir == false ]]; then
    main
else
    [[ -d $_d_config ]] || {
        echo "$filename: confdir \`$_d_config' does not exist"
        exit 1
    }
    for conf in "$_d_config"/*.conf
    do
        . "$conf"
        main
        unset subvol dest nkeep writable
    done
fi

exit

# vim: set ft=sh ts=4 sw=4 et:
